name: Go Build and Test
on:
  workflow_call:
    inputs:
      go_project_dir_root:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Get Dependencies
        working-directory: ${{ inputs.go_project_dir_root }}
        run: go get -d ./...
      - name: Build
        working-directory: ${{ inputs.go_project_dir_root }}
        run: go build -v ./...
      - name: Run tests
        working-directory: ${{ inputs.go_project_dir_root }}
        run: go test -v ./...
