name: Go
on: 
  workflow_call:
    inputs:
      go_project_dir_root:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.16.x'
      - name: Install dependencies
        working-directory: ${{ inputs.go_project_dir_root }}
        run: go get .
      - name: Build
        working-directory: ${{ inputs.go_project_dir_root }}
        run: go build -v ./...
      - name: Run tests
        working-directory: ${{ inputs.go_project_dir_root }}
        run: go test -v ./...
