on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      account-id:
        required: true
        type: string

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/useheartbeat/heartbeat-go-cdk-dockerfile:main
      credentials:
        username: hbh-github
        password: ${{ secrets.GH_TOKEN }}

    permissions:
      id-token: write
      contents: read

    name: Deploy
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
                        ${{ runner.os }}-go-

      - name: Get modules
        working-directory: ./cdk-infra
        run: |
          go mod download       

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ inputs.account-id }}:role/GitHubRole
          role-session-name: actions-${{ inputs.env }}
          aws-region: 'us-east-1'

      - name: Clear context
        working-directory: ./cdk-infra
        run: cdk context --clear

      - name: Deploy GW stack
        working-directory: ./cdk-infra
        run: cdk deploy --require-approval never -c envName=${{ inputs.env }} HBHClientImportVpcStack HBHClientApiGwStack

