on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Slack status
        if: always()
        uses: act10ns/slack@v2.0.0
        with:
          status: starting
          channel: '#github-actions'
          message: Starting MWAA S3 upload...
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::078979183997:role/GitHubRole
          aws-region: us-east-1
          role-session-name: actions-data

      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set short SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get branch name
        id: branch
        run: echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Upload to S3
        id: push
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Uploading DAGs..."
          aws s3 cp dags/ s3://data-us-east-1-hbh-dags/dags --recursive
          echo "Uploading requirements.txt..."
          aws s3 cp requirements.txt s3://data-us-east-1-hbh-dags
          echo "Uploading startup.sh"
          aws s3 cp mwaa/startup.sh s3://data-us-east-1-hbh-dags
          echo "Zipping and uploading plugins..."
          zip -r plugins.zip plugins
          aws s3 cp plugins.zip s3://data-us-east-1-hbh-dags

      - name: Update MWAA env
        id: update-mwaa
        if: github.ref == 'refs/heads/master'
        run: |
          export plugins_version=$(aws s3api list-object-versions --bucket data-us-east-1-hbh-dags --prefix plugins | jq -r '.Versions[0].VersionId')
          export startup_version=$(aws s3api list-object-versions --bucket data-us-east-1-hbh-dags --prefix startup | jq -r '.Versions[0].VersionId')
          export requirements_version=$(aws s3api list-object-versions --bucket data-us-east-1-hbh-dags --prefix requirements | jq -r '.Versions[0].VersionId')
          aws mwaa update-environment --name data-us-east-1-mwaa --plugins-s3-object-version $plugins_version --requirements-s3-object-version $requirements_version --startup-script-s3-object-version $startup_version

          status="NA"
          while [ "$status" != "AVAILABLE" ]
          do
              echo "MWAA updating..."
              status=$(aws mwaa get-environment --name data-us-east-1-mwaa | jq '.[].Status')
              sleep 20  
          done
          echo "MWAA updated..."

      - name: Post final status
        if: always()
        uses: act10ns/slack@v2.0.0
        with:
          status: ${{ job.status }}
          channel: '#github-actions'
          message: Upload ${{ job.status }}, logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
