on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      env:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Slack status
        if: always()
        uses: act10ns/slack@v2.0.0
        with:
          status: starting
          channel: '#github-actions'
          message: Restarting ${{ inputs.service }} in ${{ inputs.env }}...
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Determine IAM Role
        id: iam
        env:
          ENV: ${{ inputs.env }}
        run: |
          [[ "$ENV" == "prod" ]] && echo "iam_role=arn:aws:iam::098444936620:role/GitHubRole" >> $GITHUB_OUTPUT || echo "iam_role=arn:aws:iam::701248519518:role/GitHubRole" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ steps.iam.outputs.iam_role }}
          aws-region: us-east-1
          role-session-name: actions-${{ inputs.env }}

      - name: Restart Service
        id: service-restart
        env:
          SERVICE: hb-${{ inputs.service }}
          IMAGE_TAG: ${{ inputs.image-tag }}
          ENV: ${{ inputs.env }}
        run: |
          AWS_DEFAULT_REGION=us-east-1
          aws eks --region us-east-1 update-kubeconfig --name $ENV-us-east-1-eks
          kubectl rollout restart deployment $SERVICE -n $ENV