name: lint
on:
  workflow_call:
    inputs:
      env:
        required: false
        type: string
      rust_version:
        required: false
        type: string
        default: stable
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install latest stable
        uses: dtolnay/rust-toolchain@${{inputs.rust_version}}
        with:
          components: rustfmt, clippy
      - name: Run rustfmt
        run: cargo fmt --check
      - name: Run clippy
        run: cargo clippy --all-features
