name: Rust Build Test
on:
  workflow_call:
    inputs:
      env:
        required: false
        type: string
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  SCCACHE_BUCKET: "hbh-sccache"
  SCCACHE_REGION: "us-east-1"
  SCCACHE_S3_KEY_PREFIX: ${{ github.event.repository.name }}
jobs:
  build:
    runs-on: ubuntu-latest-m
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::631720813209:role/GitHubRole
          aws-region: us-east-1
          role-session-name: actions-${{ inputs.env }}

      - name: Install latest stable
        uses: dtolnay/rust-toolchain@stable

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run test
        run: cargo test --all-features --workspace
