name: lint
on:
  workflow_call:
    inputs:
      env:
        required: false
        type: string
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install latest stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
