name: Monitor OpenAPI changes
on:
  workflow_call:
    inputs:
      env:
        required: false
        type: string
      rust_version:
        required: false
        type: string
        default: stable
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
jobs:
  openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install latest stable
        uses: dtolnay/rust-toolchain@${{github.event.inputs.rust_version}}
      - name: Copy openapi.yaml
        run: cp openapi.yaml openapi.yaml_bak
        shell: bash
      - name: Generate OpenAPI specification
        run: cargo run --bin gen-openapi --verbose
      - name: Compare files
        run: diff --side-by-side openapi.yaml openapi.yaml_bak