name: Rust Build Test
on:
  workflow_call:
    inputs:
      env:
        required: false
        type: string
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install latest stable
        uses: dtolnay/rust-toolchain@1.78.0
      - name: Run build
        run: cargo build --verbose --all-features
      - name: Run test
        run: cargo test --verbose --all-features
