name: lint
on:
  workflow_call:
    inputs:
      env:
        required: false
        type: string
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
