name: lint
on:
  workflow_call:
    inputs:
      env:
        required: false
        type: string
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  SCCACHE_BUCKET: "hbh-sccache"
  SCCACHE_REGION: "us-east-1"
  SCCACHE_S3_KEY_PREFIX: ${{ github.event.repository.name }}
jobs:
  lint:
    name: lint
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::631720813209:role/GitHubRole
          aws-region: us-east-1
          role-session-name: actions-${{ inputs.env }}

      - name: Install latest stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Run rustfmt
        run: cargo fmt --check --all

      - name: Run clippy
        run: cargo clippy --all-targets --all-features --all
