on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::631720813209:role/GitHubRole
          aws-region: us-east-1
          role-session-name: actions-${{ inputs.env }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set short SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        # run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)" DEPRECATED

      - name: Get branch name
        id: branch
        run: echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Checkout
        id: checkout-master
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}
      
      - name: store master commit sha
        id: masterSha
        run: echo "master_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        
      - name: Checkout
        id: checkout-mybranch
        uses: actions/checkout@v3
        
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Check if branch is up to date
        id: checkCurrent
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          set -x
          DEFAULT_BRANCH=${{ github.event.repository.default_branch }}
          git fetch
          git checkout $DEFAULT_BRANCH
          git checkout -
          #git merge-base --is-ancestor ${{ steps.masterSha.outputs.master_sha }} HEAD
          {git merge-base --is-ancestor master HEAD && status_code=0 }} || status_code=1
          #status_code=$?
          if [ $status_code -eq 0 ]; then
            echo "current='True'" >> $GITHUB_OUTPUT
          else
            echo "current='False'" >> $GITHUB_OUTPUT
          fi
          env
        shell: bash
