on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      env:
        required: true
        type: string
      iam-role:
        required: true
        type: string
      image-tag:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout service repo
        uses: actions/checkout@v3
        with:
          path: ${{ inputs.service }}

      - name: Check out helmfile repo
        uses: actions/checkout@v3
        with:
          repository: useheartbeat/helmfile
          token: ${{ secrets.GH_TOKEN }}
          path: helmfile

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ inputs.iam-role }}
          aws-region: us-east-1
          role-session-name: actions-${{ inputs.env }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.20.0'
        id: install

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.0.0

      - name: Get branch name
        id: branch
        run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Run test script
        env:
          SERVICE: hb-${{ inputs.service }}
          IMAGE_TAG: ${{ inputs.image-tag }}
          ENV: ${{ inputs.env }}
        run: |
          ls ${GITHUB_WORKSPACE}/
          ls ${GITHUB_WORKSPACE}/${{ inputs.service }}/
          # chmod +x ${GITHUB_WORKSPACE}/${{ inputs.service }}/.github/scripts/integ-test.sh
          # ${GITHUB_WORKSPACE}/${{ inputs.service }}/.github/scripts/integ-test.sh $ENV us-east-1 test $SERVICE $IMAGE_TAG
        shell: bash

      - name: Display test reports
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'helmfile/**/build/test-results/**/*.xml'