on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::631720813209:role/GitHubRole
          aws-region: us-east-1
          role-session-name: actions-${{ inputs.env }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set short SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        # run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)" DEPRECATED

      - name: Get branch name
        id: branch
        run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: hb-${{ inputs.service }}
          IMAGE_TAG: ${{ steps.sha.outputs.sha_short }}
        run: |
          echo "building and pushing to: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg githubUsername=hbh-github --build-arg githubToken=${{ secrets.GH_TOKEN }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

# if branch name matches "test/**" pattern, then skip deploying dev in "dev" namespace
# and just deploy to test namespace
      - name: Trigger deploy to test namespace in Dev
        if: startsWith(steps.branch.outputs.branch, 'test')
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: useheartbeat/heartbeat-${{ inputs.service }}
          event-type: trigger-dev-deploy
          client-payload: '{"sha": "${{ steps.sha.outputs.sha_short }}",
                            "test": "true"}'

# if branch name matches "hotfix/**", "feature/**", or "fix/**" pattern, then deploy to dev in "dev" namespace
# and trigger tests in test namespace afterwards
      - name: Trigger deploy to Dev
        if: |
          startsWith(steps.branch.outputs.branch, 'hotfix') ||
          startsWith(steps.branch.outputs.branch, 'feature') ||
          startsWith(steps.branch.outputs.branch, 'fix')
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: useheartbeat/heartbeat-${{ inputs.service }}
          event-type: trigger-dev-deploy
          client-payload: '{"sha": "${{ steps.sha.outputs.sha_short }}",
                            "test": "false"}'

# if on the main branch, deploy to prod with no tests
      - name: Trigger deploy to Prod
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: useheartbeat/heartbeat-${{ inputs.service }}
          event-type: trigger-prod-deploy
          client-payload: '{"sha": "${{ steps.sha.outputs.sha_short }}",
                            "test": "false"}'
