on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      env:
        required: true
        type: string
      iam-role:
        required: true
        type: string
      image-tag:
        required: false
        type: string
      pr:
        required: true
        type: string
      close:
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-22.04

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Slack status
        if: always()
        uses: act10ns/slack@v2.0.0
        with:
          status: starting
          channel: '#github-actions'
          message: Starting Preview for ${{ inputs.service }}:${{ inputs.image-tag }} PR ${{ inputs.pr }}...
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Checkout service repo
        id: checkout-app
        uses: actions/checkout@v4
        with:
          path: ${{ inputs.service }}

      - name: Check out helmfile repo
        id: checkout-helm
        uses: actions/checkout@v4
        with:
          repository: useheartbeat/helmfile
          token: ${{ secrets.GH_TOKEN }}
          path: helmfile

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.iam-role }}
          aws-region: us-east-1
          role-session-name: actions-${{ inputs.env }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.20.0'
        id: install-kubectl

      - name: Setup helmfile
        id: setup-helm
        uses: mamezou-tech/setup-helmfile@v2.0.0

      - name: Run preview script
        if: inputs.close != true
        id: preview
        env:
          SERVICE: hb-${{ inputs.service }}
          IMAGE_TAG: ${{ inputs.image-tag }}
          PR: ${{ inputs.pr }}
        run: |
          chmod +x ${GITHUB_WORKSPACE}/${{ inputs.service }}/.github/scripts/pr-preview.sh
          ${GITHUB_WORKSPACE}/${{ inputs.service }}/.github/scripts/pr-preview.sh $PR us-east-1 preview $SERVICE $IMAGE_TAG
        shell: bash

      - name: Add PR comment
        if: inputs.close != true
        id: preview-link
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Check out the PR preview at: ${{ steps.preview.outputs.preview_url }}

      - name: Cleanup preview
        if: ${{ inputs.close }}
        id: preview-remove
        env:
          SERVICE: hb-${{ inputs.service }}
          ENV: ${{ inputs.env }}
          PR: ${{ inputs.pr }}
        run: |
          aws eks --region us-east-1 update-kubeconfig --name $ENV-us-east-1-eks
          kubectl get ns | grep $PR-preview-$SERVICE
          if [ $? -eq 0 ]; then
            kubectl delete ns $PR-preview-$SERVICE
          else
            echo "No namespace to clean up"
          fi
        shell: bash

      - name: Post final status
        if: always()
        uses: act10ns/slack@v2.0.0
        with:
          status: ${{ job.status }}
          channel: '#github-actions'
          message: Preview ${{ job.status }}, logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
