on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      env:
        required: true
        type: string
      iam-role:
        required: true
        type: string
      image-tag:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Post status to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # The following message update step does not accept a channel name.
          # Setting a channel ID here for consistency is highly recommended.
          channel-id: ${{ secrets.SLACK_STATUS_CHANNEL }}
          payload: |
            {
              "text": "Tests started (In Progress)",
              "attachments": [
                {
                  "pretext": "Tests started for ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "In Progress"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Checkout service repo
        uses: actions/checkout@v3
        with:
          path: ${{ inputs.service }}

      - name: Check out helmfile repo
        uses: actions/checkout@v3
        with:
          repository: useheartbeat/helmfile
          token: ${{ secrets.GH_TOKEN }}
          path: helmfile

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ inputs.iam-role }}
          aws-region: us-east-1
          role-session-name: actions-${{ inputs.env }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.20.0'
        id: install

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0

      - name: Get branch name
        id: branch
        run: echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Run test script
        id: test
        env:
          SERVICE: hb-${{ inputs.service }}
          IMAGE_TAG: ${{ inputs.image-tag }}
          ENV: ${{ inputs.env }}
        run: |
          chmod +x ${GITHUB_WORKSPACE}/${{ inputs.service }}/.github/scripts/integ-test.sh
          ${GITHUB_WORKSPACE}/${{ inputs.service }}/.github/scripts/integ-test.sh $ENV us-east-1 test $SERVICE $IMAGE_TAG
        shell: bash

      - name: Post build status to Slack
        if: always()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_STATUS_CHANNEL }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Tests finished (Completed)",
              "attachments": [
                {
                  "pretext": "Tests finished for ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "${{ steps.test.outcome }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Display test reports
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/**/*.xml'
          token: ${{ secrets.GH_TOKEN }}