on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      env:
        required: true
        type: string
      iam-role:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      branch:
        required: true
        type: string
      namespace:
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-24.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Slack status
        if: ${{ github.actor != 'renovate[bot]' }}
        uses: act10ns/slack@v2.1.0
        with:
          status: starting
          channel: '#github-actions'
          message: Starting Deploy for ${{ inputs.service }}:${{ inputs.image-tag }} branch ${{ inputs.branch }} to ${{ inputs.env }}...
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v2.1.0
        with:
          helm-s3-plugin-version: v0.16.2

      - name: Check out helmfile repo
        id: checkout-helm
        uses: actions/checkout@v4
        with:
          repository: useheartbeat/helmfile
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.iam-role }}
          aws-region: us-east-1
          role-session-name: actions-${{ inputs.env }}

      - name: Helmfile sync
        id: Helm-sync
        env:
          SERVICE: hb-${{ inputs.service }}
          IMAGE_TAG: ${{ inputs.image-tag }}
          ENV: ${{ inputs.env }}
          NAMESPACE: ${{ inputs.namespace }}
        run: |
          NS=${NAMESPACE:-$ENV}
          AWS_DEFAULT_REGION=us-east-1 helm repo add hbh s3://hbh-helm-charts
          aws eks --region us-east-1 update-kubeconfig --name $ENV-us-east-1-eks
          env=$ENV region=us-east-1 ns=$NS image_tag=$IMAGE_TAG helmfile -f stable/$SERVICE.yaml sync

      - name: Post failed status dev
        if: ${{ always() && steps.Helm-sync.outcome != 'success' && github.actor != 'renovate[bot]' && inputs.env == 'dev'}}
        uses: act10ns/slack@v2.1.0
        with:
          status: ${{ steps.Helm-sync.outcome }}
          channel: '#alerts-warning'
          message: Deploy ${{ steps.Helm-sync.outcome }}, logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_WARNING }}

      - name: Post failed status prod
        if: ${{ always() && steps.Helm-sync.outcome != 'success' && github.actor != 'renovate[bot]' && inputs.env == 'prod'}}
        uses: act10ns/slack@v2.1.0
        with:
          status: ${{ steps.Helm-sync.outcome }}
          channel: '#alerts-severe'
          message: Deploy ${{ steps.Helm-sync.outcome }}, logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SEVERE }}

      - name: Post status
        if: always() && github.actor != 'renovate[bot]'
        uses: act10ns/slack@v2.1.0
        with:
          status: ${{ job.status }}
          channel: '#github-actions'
          message: Deploy ${{ job.status }}, logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
