on:
  workflow_call:
    inputs:
      test-run:
        required: true
        type: string
      sha:
        required: true
        type: string
      branch:
        required: true
        type: string
      test-path:
        required: true
        type: string
    outputs:
      failed-count: 
        description: Number of failed tests
        value: ${{ jobs.report.outputs.failed-count }}

jobs:
  report:
    runs-on: ubuntu-22.04

    outputs:
      failed-count: ${{ steps.failed-count.outputs.failed }}

    permissions: write-all
      # id-token: write
      # contents: write
      # checks: write

    steps:
      - name: Checkout service repo
        id: checkout-app
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}
          path: hb

      - name: Checkout working sha
        id: checkout-sha
        run: |
          cd hb && git checkout ${{ inputs.sha }}

      - name: Sleep
        run: sleep 60

      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: hb

      - name: Get Results
        id: results
        uses: dorny/test-reporter@v1.7.0
        with:
          name: JUnit Tests
          working-directory: ${{steps.download-artifact.outputs.download-path}}
          path: ${{ inputs.test-path }}
          reporter: java-junit
          list-tests: 'failed'
          list-suites: 'failed'
          max-annotations: '50'

      - name: Export failed test count
        id: failed-count
        run: echo "failed=${{ steps.results.outputs.failed }}" >> $GITHUB_OUTPUT

      - name: Post result status
        id: slack-results
        if: ${{ steps.results.outcome == 'success' || steps.results.outcome == 'failed' }}
        uses: act10ns/slack@v2.0.0
        with:
          status: ${{ steps.results.outcome }}
          channel: '#github-actions'
          message: ${{ steps.results.outputs.passed }} out of ${{ steps.results.outputs.total }} tests passed. ${{ steps.results.outputs.failed }} failed. Logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Post final status
        id: slack-results-final
        if: ${{ steps.slack-results.outcome == 'skipped' }}
        uses: act10ns/slack@v2.0.0
        with:
          status: ${{ job.status }}
          channel: '#github-actions'
          message: Failed to complete reporting for tests. Logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}