on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      env:
        required: true
        type: string
      iam-role:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Slack status
        if: always()
        uses: act10ns/slack@v2.0.0
        with:
          status: starting
          channel: '#github-actions'
          message: Starting Tests for ${{ inputs.service }}:${{ inputs.image-tag }} branch ${{ inputs.branch }} on ${{ inputs.env }}...
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Checkout service repo
        id: checkout-app
        uses: actions/checkout@v3
        with:
          path: ${{ inputs.service }}

      - name: Check out helmfile repo
        id: checkout-helm
        uses: actions/checkout@v3
        with:
          repository: useheartbeat/helmfile
          token: ${{ secrets.GH_TOKEN }}
          path: helmfile

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ inputs.iam-role }}
          aws-region: us-east-1
          role-session-name: actions-${{ inputs.env }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.20.0'
        id: install-kubectl

      - name: Setup helmfile
        id: setup-helm
        uses: mamezou-tech/setup-helmfile@v1.2.0

      - name: Run test script
        id: test
        continue-on-error: true
        env:
          SERVICE: hb-${{ inputs.service }}
          IMAGE_TAG: ${{ inputs.image-tag }}
          ENV: ${{ inputs.env }}
        run: |
          chmod +x ${GITHUB_WORKSPACE}/${{ inputs.service }}/.github/scripts/integ-test.sh
          ${GITHUB_WORKSPACE}/${{ inputs.service }}/.github/scripts/integ-test.sh $ENV us-east-1 test $SERVICE $IMAGE_TAG
        shell: bash

      - name: Upload test results
        id: results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: '**/build/test-results/**/*.xml'

      - name: Post result status
        id: slack-results
        if: ${{ steps.test.conclusion == 'success' && steps.results.outcome == 'success' }}
        uses: act10ns/slack@v2.0.0
        with:
          status: ${{ steps.test.outcome }}
          channel: '#github-actions'
          message: ${{ steps.results.outputs.passed }} out of ${{ steps.results.outputs.total }} tests passed. ${{ steps.results.outputs.failed }} failed. Logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Trigger Test Results
        if: ${{ steps.test.conclusion == 'success' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: useheartbeat/heartbeat-${{ inputs.service }}
          event-type: trigger-test-results
          client-payload: '{"sha": "${{ inputs.image-tag }}",
                            "branch": "${{ inputs.branch }}"}'

      - name: Post final status
        if: ${{ steps.slack-results.outcome == 'skipped' || steps.test.outcome == 'failed' }}
        uses: act10ns/slack@v2.0.0
        with:
          status: ${{ job.status }}
          channel: '#github-actions'
          message: Failed to get test results for ${{ inputs.service }}:${{ inputs.image-tag }} on ${{ inputs.env }}. Logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # if on the main branch, deploy to prod with
      - name: Trigger deploy to Prod
        if: ${{ (startsWith(inputs.branch, 'master') || startsWith(inputs.branch, 'main')) && steps.results.outputs.failed == 0 }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: useheartbeat/heartbeat-${{ inputs.service }}
          event-type: trigger-prod-deploy
          client-payload: '{"sha": "${{ inputs.image-tag }}",
                            "branch": "${{ inputs.branch }}"}'
