on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  aws_cdk:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    name: Deploy
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Get modules and build
        working-directory: ./cdk-infra
        run: |
          npm install -g aws-cdk && npm install && npm run build

      - name: Determine IAM Role
        id: iam
        env:
          ENV: ${{ inputs.env }}
        run: |
          [[ "$ENV" == "prod" ]] && echo "iam_role=arn:aws:iam::098444936620:role/GitHubRole" >> $GITHUB_OUTPUT || echo "iam_role=arn:aws:iam::701248519518:role/GitHubRole" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ steps.iam.outputs.iam_role }}
          aws-region: us-east-1
          role-session-name: actions-${{ inputs.env }}

      - name: Clear context
        working-directory: ./cdk-infra
        run: cdk context --clear

      - name: Synth
        working-directory: ./cdk-infra
        run: cdk synth

      - name: Deploy
        id: cdk-deploy
        working-directory: ./cdk-infra
        run: cdk deploy --require-approval never --all

      - name: Post failed status
        if: ${{ always() && steps.cdk-deploy.outcome != 'success' && github.actor != 'renovate[bot]'}}
        uses: act10ns/slack@v2.1.0
        with:
          status: ${{ steps.cdk-deploy.outcome }}
          channel: '#alerts-severe'
          message: CDK Deploy ${{ steps.cdk-deploy.outcome }}, logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SEVERE }}
        
